apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: github-rest-api
  description: GitHub REST API pública v3
  tags:
    - rest
    - github
spec:
  type: openapi
  lifecycle: production
  owner: github
  definition:
    $text: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml
